### PR TITLE
Review of the current code

### PR DESCRIPTION
**Pull request by courtiol**
The description will be updated progressively.

Main changes:
- [x] add RStudio project for local use of `{usethis}` and other tools that require the folder to be a project.
- [x] replace  `{magrittr}` pipes  by native pipes.
- [x] remove dependency to `{rgdal}` which is retired: https://cran.r-project.org/web/packages/rgdal/index.html
- [x] replace `{raster}` with `{stars}` since the former package is now superseeded.

### CODE REVIEW

**Comment by derele** [comment]
Very cool. Learning new stuff: native pipes, I've seen them in the wild before but didn't pay enough attention. And these pull request drafts themselves :+1:

**Comment by courtiol** [comment]
@derele I just rewrote file 2 using stars.

It takes 6 hours to run, somehow `aggregate()` is very inefficient, but I would stick to that since it creates simple code.
The method used in `aggregate()` may also become much faster in the near future.
I stored the data created as intermediate data, so you can check them.
You could also check the plots I put in to see if things are fine.
I am not sure how proportion were computed before, it was to complicated for me, but I hope the logic is still the same.

To avoid the 6 hours-long step (on 1 CPU), perhaps we should not project a raster into a series of polygons.
It would be much efficient to directly aggregate a raster without using a `Britain10grid` .
I don't know why we do that in the first place, but perhaps I will understand while moving on the the next steps.
Perhaps `Britain10grid` is connected to the GBIF data...?

If we need to stick to the approach, we could parallelize the aggregation so as to dispatch 1 layer per CPU, but it would only save less than one order of magnitude in terms of computation time, and it would be memory greedy, so it is probably not worth it.

**Comment by derele** [comment]
We use the `Britain10grid` to count Gbif observations within it. We simply need the proportions of land-use and Gbif counts in the same grids. I think @Annie-droid98 decided to use available eea-reference grids to potentially align with work others are doing?! 

It would definitely be possible to set up our own grids if this is easier! But I don't understand how to "directly aggregate a raster" and then count observations in the same aggregate grids. But this is probably only because I don't understand the difference between projection and aggregation?

**Comment by courtiol** [comment]
The difference here is not between projection and aggregation.
The difference is between defining the grid based on the raster itself (e.g. if cells are 100m x 100m one could aggregate sets of 100 cells x 100 cells into a 10km x 10km cell) without any grid *vs* overlapping an external grid onto a raster and aggregating the cells (or parts of cells) that fall within each cell defined by the external grid.

So it is a difference between doing something like this:
```r
st_downsample(clc_2018_landcover |> select(-landcover, -landcover_cat), n = 99, FUN = mean)
```
which takes 1 minute of computation and takes little memory, and doing something like this:
```r
aggregate(clc_2018_landcover |> select(-landcover, -landcover_cat), by = Britain10grid, FUN = mean)
```
which takes hours and use a huge amount of memory.

Prediction-wise it leads to very little difference unless we focus on small details:

- method 1
image

- method 2
image


Since method 1 can be done on a laptop and method 2 requires a server, I would be quite keen trying to attempt dropping the use of a grid external to that defined by the raster altogether.

That would also simplify the code even further as it would drop script 1.

This whole thing is a little bit of an experiment since I have not yet look at the next steps, but the idea of making most of the code progressively disappearing appeals to me (although I understand that it can be frustrating for those who wrote the code I make disappear).

What do you think?

**Comment by courtiol** [comment]
(in any case, I should have a close look at the GBIF data before possibly dropping the grid if it is a viable option)

**Comment by derele** [comment]
Ah okay. I'll probably understand better once I run the code myself. As far as I get it the `st_downsample` "works in the raster itself" using a "pseudo-grid" defined by lowering the previously high resolution.  

In `2b_CountGbif.R` we currently work with "grid identity", with a label each grid has (l51 `group_by(CELLCODE, year, Observer, FocusTaxaTorF, .drop=FALSE) `). I'm not sure how you'd do this without knowing a cell's identity. I imagine something like putting the counts "on the raster" (?),  doing the same `st_downsample` and then count over a "raster including counts and landuse"? Basically using raster operations for both the landuse and counts instead of table operations for the latter?

**Comment by courtiol** [comment]
raster vs table is not the issue since turning the raster into a table takes 1 sec. But yes it will depends on how efficient it will be to count observations falling into a raster cell (be it formatted as raster or simple feature table) if we cannot rely on a CELLCODE and thus must rely on computing intersections. I will check, but I am optimistic.

**Comment by derele** [comment]
Could we merge the older, compute-intensive cell-count approach? I would like to get back to this towards the end of the week.

**Comment by courtiol** [comment]
I will try to give a try this week to continue with the same approach. If I don't manage, I can merge and you can try, OK?
Are you around these days? We could also move forward together.

**Comment by derele** [comment]
Sounds good, thx! Co-working on this would be fun, but I'm just recovering from the flu and will be in Vienna next week for a talk.

**Pull request merged**
